### ISSUE TITLE
Error in causalForest: lexical sort of variable names instead of value sort

### ISSUE THREAD

**Issue by amilymoor** [susanathey/causalTree#16]
I observe the following in causalForest.R:

In line 19, 23, 52, and 189, the code sorts variable names (x1, x2,...) in lexicographic order, and re-organizes the data columns before feeding the data to tree-building procedure. For example, for a data with 10 Xs, this will change the column order in the input data from (x1, x2, ..., x10) to (x1, x10, x2, x3, ..., x9). This shuffling of columns will make the variable names used in tree split (which are reported in cf$trees, cf$fsample, and cf$nameall_sample) inconsistent with the outside data colnames. This is because:

In line 125 & 127, "cov_sample" is used as the column indices when selecting X to feed to a single tree, and these indices are recorded in fsample and nameall_sample (line 88-106) as colnames: X#. However, at this point, these indices do not match the actual colnames in the input data. Following from the above example, a tree might be using x10, x2, x3 (whose column indices are now 2, 3, 4) to split the data, while nameall_sample would save them as x2, x3, x4. 

The program thus reports error when I try to predict(cf, newdata, type="vector"), with x1-x9 to be numeric variables and x10 a factor variable. (newdata = c(x1, x2, ..., x10, y).) I encounter the following error message:

"Error: variable 'x2' was fitted with type "factor" but type "numeric" was supplied
In addition: Warning message:
In model.frame.default(Terms, newdata, na.action = na.action, xlev = attr(object,  :
  variable 'x2' is not a factor"

Which seems to imply that in tree-building&estimation, it takes x10 as x2; while in prediction, it tries to use the real x2 and realizes that it does not match the data type used in model building. Removing the sorting process (while guaranteeing that the input data has been properly sorted from x1 to x10) fixed the error.

**Comment by susanathey** [comment]
Fixed.  Let us know if you see any problems!

**Comment by amilymoor** [comment]
Perfect. Thank you!
