### ISSUE TITLE
Memory leak in causalForest?

### ISSUE THREAD

**Issue by roboton** [susanathey/causalTree#28]
I've tried running causalForest with a single factor variable (21 levels) and a treatment indicator and find myself running out of memory very quickly.  I tested this on a machine with 16GB of ram and 20GB of swap space and ran out of memory within a minute.  If there is some known progress on this issue I'm happy to pick up where it left off!

**Comment by swager** [comment]
If you want to do larger-scale forests, I recommend you use the causal_forest function in our new `grf` package instead (available from CRAN). The causalTree package has many functions that are useful for studying single trees; however, for building a full forest `grf` scales much better (and also has methodological improvements described <a href="https://arxiv.org/pdf/1610.01271.pdf">here</a>).

**Comment by roboton** [comment]
Ah wonderful.  Thanks so much @swager.  You were a great TA for STATS 217 a few years ago too!
