### ISSUE TITLE
all.Rdata error

### ISSUE THREAD

**Issue by coeyjoops** [susanathey/causalTree#35]
In the source code, there is this line.
Line 312: save(list = ls(all.names = TRUE),file="all.Rdata")
It would appear that this line was for interactive debugging since there are a few other lines that are commented out and do similar things and "all.Rdata" is in the main part of the repo. When trying to use this package on a remote server where I do not have full permissions, this causes an error and makes me unable to use the package. Fixing this issue should allow all users to use the functions in the package.
I was able to get around this issue by changing the working directory to something writable by the serve I was using (a temporary folder) but there may be a way for you to fix this issue so it does not come up for other users.

**Comment by IyarLin** [comment]
Yeah, I'm also getting all sorts of headache from that line. Thanks for finding it, I'll try removing it from my copy of the package
