### ISSUE TITLE
Error in honest.causalTree when na.action removes rows

### ISSUE THREAD

**Issue by dkassler** [susanathey/causalTree#7]
When calling `honest.causalTree` and rows are removed from the data as a result of `na.action`, there's a mismatch between the number of rows in the data and the length of the vector specified in the `treatment` argument, which retains its original length. This causes the function to fail when it hits ```if (sum(treatment) == 0 || sum(treatment) == nobs)``` at line 48 of `honest.causalTree.R`.

Here's a minimal example:
```{r}
library(causalTree)

s <- iris
s$id <- 1:nrow(s)
s[1, 1] <- NA  # *** Either this line or the next one will cause code to fail
s[2, -1] <- NA # ***
s$treatment <- sample(0:1, nrow(s), replace = T)

s_tr <- s[sample(nrow(s), round(nrow(s)/2)), ]
s_est <- s[!(s$id %in% s_tr$id), ]

honest.causalTree(
  formula = Sepal.Length ~ Sepal.Width + Petal.Length,
  data = s_tr,
  treatment = s_tr$treatment,  
  est_data = s_est,
  est_treatment = s_est$treatment,
  split.Rule = "CT",
  split.Honest = TRUE
)
##Error in honest.causalTree(formula = Sepal.Length ~ Sepal.Width + Petal.Length,  : 
##  The treatment status should be 1 or 0 only: 1 represent treated and 0 represent controlled.
```

**Comment by mukherjee-d** [comment]
Fixed the bug-- the code should work fine now!
