### ISSUE TITLE
predict.causalForest breaks on test data frames unless they are renamed

### ISSUE THREAD

**Issue by dkassler** [susanathey/causalTree#8]
When a `newdata` data frame is passed to `predict.causalForest`, the function looks for variables with generic names "x1", "x2", etc. instead of the variables used to fit the tree. This results in an error like  "`Error in eval(expr, envir, enclos) : object 'x9' not found`". Renaming the variables in `newdata` causes the function to run without errors, but leaves me no guarantee that I'm actually using the correct variables to predict, so I can't consider it a viable workaround.

Here's a small example that shows the error:

```
library(causalTree)

all_vars <- names(mtcars)[-c(1, 8)]
fmla <- formula(paste0("mpg ~ ", paste(all_vars, collapse = "+")))
s_tr <- mtcars[1:25,]
s_te <- mtcars[26:32, ]

cf <- causalForest(
  formula = fmla,
  data = s_tr,
  treatment = s_tr$vs,
  split.Rule = 'CT',
  split.Honest = TRUE,
  split.Bucket = F,
  bucketNum = 5,
  bucketMax = 100,
  cv.option = 'CT',
  cv.Honest = TRUE,
  minsize = 2L,
  split.alpha = 0.5,
  cv.alpha = 0.5,
  sample.size.total = floor(nrow(s_tr) / 2),
  sample.size.train.frac = .5,
  mtry = ceiling(ncol(s_tr) / 2),
  nodesize = 3,
  num.trees = 5,
  ncolx = length(all_vars),
  ncov_sample = ceiling(length(all_vars) / 2)
)

predict(cf, s_te)
##Error in eval(expr, envir, enclos) : object 'x9' not found

names(s_te)[-c(1,8)] <- paste0("x", 1:(ncol(s_te) - 2))
predict(cf, s_te)
##[1] 7 5
##[1] 0.5833333 0.5833333 0.5833333 0.5833333 0.5833333 0.5833333 0.5833333
```

The error itself is being thrown from `predict.rpart`, and my guess is that the source of the problem lies with the creation of the trees themselves.

**Comment by mukherjee-d** [comment]
Thanks for finding this issue. We made changes to the function and it should work now!
